// src/routes/apps/Settings.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { writable } from 'svelte/store';

  const defaultSettings = {
    darkMode: false,
    volume: 50,
    notifications: true
  };

  const settings = writable(defaultSettings);

  onMount(() => {
    const saved = localStorage.getItem('settings');
    if (saved) settings.set(JSON.parse(saved));
  });

  settings.subscribe((value) => {
    localStorage.setItem('settings', JSON.stringify(value));
  });

  function toggleDarkMode() {
    settings.update(s => ({ ...s, darkMode: !s.darkMode }));
  }

  function changeVolume(e: Event) {
    const value = +(e.target as HTMLInputElement).value;
    settings.update(s => ({ ...s, volume: value }));
  }

  function toggleNotifications() {
    settings.update(s => ({ ...s, notifications: !s.notifications }));
  }

  // Tab-Logik
  let activeTab: 'general' | 'sound' | 'notifications' = 'general';
  function selectTab(tab: 'general' | 'sound' | 'notifications') {
    activeTab = tab;
  }
</script>

<div class="settings-window">
  <!-- Tabs -->
  <div class="tabs">
    <button class:active={activeTab==='general'} on:click={() => selectTab('general')}>Allgemein</button>
    <button class:active={activeTab==='sound'} on:click={() => selectTab('sound')}>Sound</button>
    <button class:active={activeTab==='notifications'} on:click={() => selectTab('notifications')}>Benachrichtigungen</button>
  </div>

  <!-- Tab Inhalte -->
  <div class="tab-content">
    {#if activeTab === 'general'}
      <div class="setting">
        <label>
          <input type="checkbox" bind:checked={$settings.darkMode} on:change={toggleDarkMode} />
          Dark Mode
        </label>
      </div>
    {/if}

    {#if activeTab === 'sound'}
      <div class="setting">
        <label>
          Volume: {$settings.volume}
          <input type="range" min="0" max="100" value={$settings.volume} on:input={changeVolume} />
        </label>
      </div>
    {/if}

    {#if activeTab === 'notifications'}
      <div class="setting">
        <label>
          <input type="checkbox" bind:checked={$settings.notifications} on:change={toggleNotifications} />
          Notifications
        </label>
      </div>
    {/if}
  </div>
</div>

<style>
.settings-window {
  width: 380px;
  padding: 16px;
  background: rgba(240,240,240,0.95);
  border-radius: 10px;
  box-shadow: 0 4px 12px rgba(0,0,0,0.25);
  color: #000;
  font-family: sans-serif;
}

.tabs {
  display: flex;
  gap: 4px;
  margin-bottom: 12px;
}

.tabs button {
  flex: 1;
  padding: 8px;
  border: none;
  border-bottom: 2px solid transparent;
  background: transparent;
  cursor: pointer;
  font-weight: bold;
  transition: all 0.2s;
}

.tabs button.active {
  border-bottom: 2px solid #0078d4;
  color: #0078d4;
}

.tabs button:hover {
  background: rgba(0,0,0,0.05);
}

.tab-content .setting {
  margin-bottom: 16px;
}

input[type="range"] {
  width: 100%;
}
</style>

// src/routes/apps/settings/Settings.jsx
import React, { useState, useEffect } from 'react';
import './Settings.css';

const defaultSettings = {
  darkMode: false,
  volume: 50,
  notifications: true,
};

export default function Settings() {
  const [settings, setSettings] = useState(() => {
    try {
      const saved = localStorage.getItem('settings');
      if (saved) return { ...defaultSettings, ...JSON.parse(saved) };
    } catch {  }
    return { ...defaultSettings };
  });

  const [activeTab, setActiveTab] = useState('general');

  useEffect(() => {
    localStorage.setItem('settings', JSON.stringify(settings));
  }, [settings]);

  const toggleDarkMode = () => setSettings((s) => ({ ...s, darkMode: !s.darkMode }));
  const changeVolume = (e) => setSettings((s) => ({ ...s, volume: Number(e.target.value) }));
  const toggleNotifications = () => setSettings((s) => ({ ...s, notifications: !s.notifications }));

  return (
    <div className="settings-window">
      <div className="settings-tabs">
        <button className={activeTab === 'general' ? 'active' : ''} onClick={() => setActiveTab('general')}>Allgemein</button>
        <button className={activeTab === 'sound' ? 'active' : ''} onClick={() => setActiveTab('sound')}>Sound</button>
        <button className={activeTab === 'notifications' ? 'active' : ''} onClick={() => setActiveTab('notifications')}>Benachrichtigungen</button>
      </div>

      <div className="settings-tab-content">
        {activeTab === 'general' && (
          <div className="setting">
            <label>
              <input type="checkbox" checked={settings.darkMode} onChange={toggleDarkMode} />
              Dark Mode
            </label>
          </div>
        )}

        {activeTab === 'sound' && (
          <div className="setting">
            <label>
              Volume: {settings.volume}
              <input type="range" min="0" max="100" value={settings.volume} onChange={changeVolume} />
            </label>
          </div>
        )}

        {activeTab === 'notifications' && (
          <div className="setting">
            <label>
              <input type="checkbox" checked={settings.notifications} onChange={toggleNotifications} />
              Notifications
            </label>
          </div>
        )}
      </div>
    </div>
  );
}
