// src/routes/desktop/Dock.svelte
<script lang="ts">
  import { scale, fade } from 'svelte/transition';
  import { cubicOut } from 'svelte/easing';
  import { onMount } from 'svelte';
  import { openTab, getCenterPosition } from '../../lib/openTab';
  import { appStore } from '../../lib/appStore';
  import { loadLastOpened, trackOpenedApp } from '../../lib/lastOpened';
  import DockItemMagnified from './DockItemMagnified.svelte';

  import Settings from '../apps/Settings.svelte';
  import Browser  from '../apps/Browser.svelte';
  import Terminal from '../apps/Terminal.svelte';
  import Finder   from '../apps/Finder.svelte';
  import Papierkorb from '../apps/Trash.svelte';
  import Apps from '../apps/Apps.svelte';
  import Github from '../apps/Github.svelte';

  type App = {
    id: number;
    name: string;
    icon: string;
    open: boolean;
    minimized: boolean;
    maximized: boolean;
    component: any;
    default: boolean;
    x: number;
    y: number;
    width: number;
    height: number;
    zIndex: number;
  };

  let nextZIndex = 100;
  let contextMenu: { appId: number; x: number; y: number } | null = null;
  let headerHeight = 28;

const baseSize = 90;
const distanceLimit = baseSize * 6;

const distanceInput = [
  -distanceLimit,
  -distanceLimit / 1.25,
  -distanceLimit / 2,
  0,
  distanceLimit / 2,
  distanceLimit / 1.25,
  distanceLimit
];

const sizeOutput = [
  baseSize,
  baseSize * 1.1,
  baseSize * 1.414,
  baseSize * 1.9,
  baseSize * 1.414,
  baseSize * 1.1,
  baseSize
];

  let dockMouseX: number | null = null;
let dockEls = new Map<number, HTMLElement>();
let dockSizes: Record<number, number> = {};

function setDockEl(id: number) {
  return (el: HTMLElement | null) => {
    if (el) dockEls.set(id, el);
    else dockEls.delete(id);
  };
}

function clamp(n: number, min: number, max: number) {
  return Math.min(max, Math.max(min, n));
}

function lerp(a: number, b: number, t: number) {
  return a + (b - a) * t;
}

function interpolatePiecewise(x: number, input: number[], output: number[]) {
  if (x <= input[0]) return output[0];
  if (x >= input[input.length - 1]) return output[output.length - 1];

  for (let i = 0; i < input.length - 1; i++) {
    const x0 = input[i], x1 = input[i + 1];
    if (x >= x0 && x <= x1) {
      const t = (x - x0) / (x1 - x0);
      return lerp(output[i], output[i + 1], t);
    }
  }
  return baseSize;
}

let raf = 0;
function scheduleDockUpdate() {
  cancelAnimationFrame(raf);
  raf = requestAnimationFrame(() => {
    const next: Record<number, number> = {};

    if (dockMouseX === null) {
      for (const app of apps) next[app.id] = baseSize;
      dockSizes = next;
      return;
    }

    for (const app of apps) {
      const el = dockEls.get(app.id);
      if (!el) { next[app.id] = baseSize; continue; }

      const r = el.getBoundingClientRect();
      const centerX = r.left + r.width / 2;
      const dist = dockMouseX - centerX;

      next[app.id] = interpolatePiecewise(dist, distanceInput, sizeOutput);
    }

    dockSizes = next;
  });
}


  let apps: App[] = [
    { id: 1, name: 'Finder', icon: '/icons/finder.webp', open: false, minimized: false, maximized: false, component: Finder, default: true, x: 0, y: 0, width: 600, height: 400, zIndex: 100 },
    { id: 2, name: 'App Store', icon: '/icons/app-store.webp', open: false, minimized: false, maximized: false, component: Apps, default: true, x: 0, y: 0, width: 800, height: 600, zIndex: 101 },
    { id: 3, name: 'Settings', icon: '/icons/settings.webp', open: false, minimized: false, maximized: false, component: Settings, default: true, x: 0, y: 0, width: 600, height: 400, zIndex: 102 },
    { id: 4, name: 'Safari', icon: '/icons/safari.webp', open: false, minimized: false, maximized: false, component: Browser, default: true, x: 0, y: 0, width: 1000, height: 700, zIndex: 103 },
    { id: 5, name: 'Terminal', icon: '/icons/terminal.webp', open: false, minimized: false, maximized: false, component: Terminal, default: false, x: 0, y: 0, width: 500, height: 350, zIndex: 104 },
    { id: 6, name: 'Github', icon: '/icons/github.webp', open: false, minimized: false, maximized: false, component: Github, default: true, x: 0, y: 0, width: 820, height: 650, zIndex: 105 },
    { id: 10, name: 'Trash', icon: '/icons/trash.webp', open: false, minimized: false, maximized: false, component: Papierkorb, default: true, x: 0, y: 0, width: 500, height: 350, zIndex: 106 },
  ];

  appStore.set(apps);

  $: appStore.set(apps);

  function draggable(node: HTMLElement, app: App) {
    let moving = false;
    const getHeaderHeight = () => {
      const header = document.querySelector('header');
      return header ? Math.ceil(header.getBoundingClientRect().height) : 28;
    };
    function handleMouseDown(e: MouseEvent) {
      if (!(e.target as HTMLElement).classList.contains('title-bar')) return;
      if (app.maximized) {
        app.maximized = false;
        apps = apps;
      }
      moving = true;
      focusApp(app.id);
      window.addEventListener('mousemove', handleMouseMove);
      window.addEventListener('mouseup', handleMouseUp);
    }
    function handleMouseMove(e: MouseEvent) {
      if (!moving) return;
      const headerHeight = getHeaderHeight();
      const nextX = app.x + e.movementX;
      const nextY = app.y + e.movementY;
      const maxX = Math.max(0, window.innerWidth - app.width);
      const maxY = Math.max(headerHeight, window.innerHeight - app.height);
      app.x = clamp(nextX, 0, maxX);
      app.y = clamp(nextY, headerHeight, maxY);
      apps = apps; 
    }
    function handleMouseUp() {
      moving = false;
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    }
    node.addEventListener('mousedown', handleMouseDown);
    return { destroy() { node.removeEventListener('mousedown', handleMouseDown); } };
  }

  function resizable(node: HTMLElement, app: App) {
    function handleMouseDown(e: MouseEvent) {
      e.preventDefault();
      e.stopPropagation();
      if (app.maximized) {
        app.maximized = false;
        apps = apps;
        return;
      }
      window.addEventListener('mousemove', handleMouseMove);
      window.addEventListener('mouseup', handleMouseUp);
    }
    function handleMouseMove(e: MouseEvent) {
      app.width = Math.max(300, e.clientX - app.x);
      app.height = Math.max(200, e.clientY - app.y);
      apps = apps;
    }
    function handleMouseUp() {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    }
    node.addEventListener('mousedown', handleMouseDown);
    return { destroy() { node.removeEventListener('mousedown', handleMouseDown); } };
  }

  function openApp(app: App) {
    if (app.open) {
      if (app.minimized) {
        app.minimized = false;
      }
      focusApp(app.id);
    } else {
      openTab(app);
      focusApp(app.id);
      trackOpenedApp({
        id: app.id,
        name: app.name,
        icon: app.icon,
        timestamp: Date.now(),
        openCount: 1
      });
      apps = apps;
    }
  }

  function closeApp(app: App) {
    app.open = false;
    apps = apps;
    appStore.set(apps);
  }

  function toggleMinimize(app: App) {
    app.minimized = true;
    apps = apps;
  }

  function toggleMaximize(app: App) {
    app.maximized = !app.maximized;
    apps = apps;
  }

  function focusApp(id: number) {
    nextZIndex++;
    if(nextZIndex > 9999) nextZIndex = 100;
    const app = apps.find(a => a.id === id);
    if (app) {
      app.zIndex = nextZIndex;
      apps = apps;
    }
  }

  function handleOpenApp(event: CustomEvent) {
    const externalApp = event.detail.app;
    if (externalApp) {
      openTab(externalApp);
      externalApp.zIndex = nextZIndex++;
      apps = [...apps];
    }
  }

  function subscribeToStore() {
    appStore.subscribe(storeApps => {
      if (storeApps && storeApps.length > 0) {
        apps = storeApps;
      }
    });
  }

  function handleDockContextMenu(event: MouseEvent, appId: number) {
    event.preventDefault();
    contextMenu = { appId, x: event.clientX, y: event.clientY };
  }

  function closeContextMenu() {
    contextMenu = null;
  }

  function handleContextAction(action: 'open' | 'close') {
    if (!contextMenu) return;
    const app = apps.find(a => a.id === contextMenu!.appId);
    if (!app) return;
    if (action === 'open') {
      openApp(app);
    } else if (action === 'close') {
      closeApp(app);
    }
    closeContextMenu();
  }

  onMount(() => {
    loadLastOpened();
    subscribeToStore();
    const handleClickOutside = () => closeContextMenu();
    document.addEventListener('click', handleClickOutside);
    
    const updateHeaderHeight = () => {
      const header = document.querySelector('header');
      if (header) headerHeight = Math.ceil(header.getBoundingClientRect().height);
    };
    updateHeaderHeight();
    window.addEventListener('resize', updateHeaderHeight);
    
    return () => {
      document.removeEventListener('click', handleClickOutside);
      window.removeEventListener('resize', updateHeaderHeight);
    };
  });
</script>

<div class="page-container">
  <div class="card-conatainer" role="none" onmousemove={(e) => (dockMouseX = e.clientX)} onmouseleave={() => (dockMouseX = null)}>
    {#each [...apps.filter(a => a.open && !a.default), ...apps.filter(a => a.default && a.name !== 'Trash'), ...apps.filter(a => a.name === 'Trash')] as app}
      <DockItemMagnified
        app_id={app.id}
        name={app.name}
        icon={app.icon}
        is_open={app.open}
        mouse_x={dockMouseX}
        is_hovering={dockMouseX !== null}
        onclick={() => openApp(app)}
        oncontextmenu={(e: MouseEvent) => handleDockContextMenu(e, app.id)}
      />
    {/each}
  </div>
</div>

{#if contextMenu}
  <div 
    class="dock-context-overlay"
    role="button"
    tabindex="0"
    onclick={closeContextMenu}
    onkeydown={(e) => e.key === 'Escape' && closeContextMenu()}
  >
    <div 
      class="dock-context-menu"
      style={`left: ${contextMenu.x}px; top: ${contextMenu.y}px;`}
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.key === 'Escape' && closeContextMenu()}
      role="menu"
      tabindex="0"
    >
      {#if contextMenu !== null && apps.find(a => a.id === contextMenu!.appId)?.open}
        <button class="context-item" role="menuitem" onclick={() => handleContextAction('close')}>
          Close
        </button>
      {/if}
      {#if contextMenu !== null && !apps.find(a => a.id === contextMenu!.appId)?.open}
        <button class="context-item" role="menuitem" onclick={() => handleContextAction('open')}>
          Open
        </button>
      {/if}
    </div>
  </div>
{/if}

{#each apps as app (app.id)}
  {#if app.open && !app.minimized}
    <div 
      class="app-window shadow-xl" 
      class:maximized={app.maximized}
      role="button"
      tabindex="0"
      aria-label={app.name}
      use:draggable={app}
      onmousedown={() => focusApp(app.id)}
      onkeydown={(e) => (e.key === 'Escape') && closeApp(app)}
      transition:scale={{ duration: 300, start: 0.9, easing: cubicOut }}
      style="left: {app.maximized ? 0 : app.x}px; 
             top: {app.maximized ? headerHeight : app.y}px; 
             width: {app.maximized ? '100vw' : app.width + 'px'}; 
             height: {app.maximized ? `calc(100vh - ${headerHeight}px)` : app.height + 'px'}; 
             z-index: {app.zIndex}"
    >
      <div class="title-bar">
        <div class="controls">
          <button class="ctrl close" aria-label="Close window" title="Close window" onclick={(e) => {e.stopPropagation(); closeApp(app);}}></button>
          <button class="ctrl minimize" aria-label="Minimize window" title="Minimize window" onclick={(e) => {e.stopPropagation(); toggleMinimize(app);}}></button>
          <button class="ctrl maximize" aria-label="Maximize window" title="Maximize window" onclick={(e) => {e.stopPropagation(); toggleMaximize(app);}}></button>
        </div>
        <span class="title-text">{app.name}</span>
      </div>
      
      <div class="window-content">
        <svelte:component this={app.component} on:openapp={handleOpenApp} />
      </div>

      <div class="resizer" use:resizable={app}></div>
    </div>
  {/if}
{/each}

<style>
   :global(::-webkit-scrollbar-button){ display:none !important; width:0 !important; height:0 !important; }
  :global(::-webkit-scrollbar-corner){ background: transparent !important; }
  :global(html, body) { overflow: hidden; }
  * { scrollbar-width: none; }
  *::-webkit-scrollbar { width: 0; height: 0; display: none; }

  .card-conatainer {
    display: flex;
    flex-direction: row;
    gap: 2px;
    justify-content: center; 
    align-items: flex-end;
    height: 76px;
    overflow: visible;
  }

  .app-window {
    position: fixed; 
    background: rgba(30, 30, 30, 0.85);
    backdrop-filter: blur(25px);
    border-radius: 12px;
    border: 0.5px solid rgba(255, 255, 255, 0.2);
    display: flex;
    flex-direction: column;
    overflow: hidden;
    box-shadow: 0 30px 60px rgba(0,0,0,0.5);
    transition: width 0.3s cubic-bezier(0.2, 0.8, 0.2, 1), 
                height 0.3s cubic-bezier(0.2, 0.8, 0.2, 1), 
                top 0.3s cubic-bezier(0.2, 0.8, 0.2, 1), 
                left 0.3s cubic-bezier(0.2, 0.8, 0.2, 1),
                border-radius 0.3s ease;
    will-change: width, height, top, left;
  }

  .app-window {
  position: fixed;
  border-radius: 12px;
  overflow: hidden;
  background: transparent;
  display: flex;
  flex-direction: column;
  box-shadow: 0 30px 60px rgba(0,0,0,0.5);
}

  .app-window:active {
    transition: none;
  }

  .app-window.maximized {
    border-radius: 0;
  }

  .title-bar {
    height: 32px;
    display: flex;
    align-items: center;
    font-size: 4em;
    font-weight: bold;
    padding: 0 12px;
    cursor: default;
    user-select: none;
    flex-shrink: 0;
  }

  .controls{
    display:flex;
    gap:8px;
    z-index:10;
  }

  .ctrl{
    width:14px;
    height:14px;
    border-radius:999px;
    border:none;
    padding:0;
    position:relative;
    display:inline-flex;
    align-items:center;
    justify-content:center;
    cursor:default;
    box-shadow:
      inset 0 0 0 0.5px rgba(0,0,0,.22),
      0 0.5px 0 rgba(255,255,255,.18);
  }

  .close{background:#ff5f57;}
  .minimize{background:#febc2e;}
  .maximize{background:#28c840;}

  .ctrl::after{
    content:"";
    width:9px;
    height:9px;
    opacity:0;
    transition:opacity 120ms ease;
    background-repeat:no-repeat;
    background-position:center;
    background-size:contain;
    filter: drop-shadow(0 0.25px 0 rgba(255,255,255,.18));
  }

  .controls:hover .ctrl::after{opacity:1; }
  .controls:hover .ctrl{
    transform: scale(1.2);
    transition: smooth 150ms ease;
  }


  .close::after{
    background-image:url("/icons/close.png");
    width:8px;
    height:8px;
  }

  .minimize::after{
    background-image:url("/icons/minimize.png");
    width:8px;
    height:8px;
  }

  .maximize::after{
    background-image:url("/icons/maximize.png");
    width:8px;
    height:8px;
  }

  .ctrl:hover{filter:brightness(.97);}


  .title-text {
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
    font-size: 13px;
    color: rgba(255, 255, 255, 0.8);
    pointer-events: none;
  }

  .window-content {
    flex: 1;
    padding: 15px;
    color: white;
    overflow: auto;
  }

  .resizer {
    position: absolute;
    right: 0;
    bottom: 0;
    width: 15px;
    height: 15px;
    cursor: nwse-resize;
    z-index: 20;
  }

  .dock-context-overlay {
    position: fixed;
    inset: 0;
    z-index: 1200;
  }

  .dock-context-menu {
    position: fixed;
    min-width: 230px;
    padding: 6px;
    border-radius: 14px;
    background: rgba(255, 255, 255, 0.15);
    border: 1px solid rgba(255, 255, 255, 0.25);
    box-shadow: 0 18px 50px rgba(0, 0, 0, 0.4);
    backdrop-filter: blur(80px) saturate(180%);
    color: rgba(20, 20, 20, 0.95);
    z-index: 1201;
    display: flex;
    flex-direction: column;
    gap: 2px;
    overflow: hidden;
    animation: menuPop 160ms ease-out;
    pointer-events: auto;
  }

  .context-item {
    width: 100%;
    display: flex;
    justify-content: flex-start;
    padding: 6px 10px;
    border-radius: 8px;
    font-size: 14px;
    color: rgba(20, 20, 20, 0.95);
    border: none;
    background: none;
    cursor: pointer;
    transition: background 140ms ease, color 140ms ease, transform 140ms ease;
  }

  .context-item:hover {
    background: rgba(200, 200, 200, 0.4);
    color: rgba(10, 10, 10, 0.99);
    transform: translateX(1px);
  }

  @keyframes menuPop {
    from {
      opacity: 0;
      transform: translateY(-6px) scale(0.98);
    }
    to {
      opacity: 1;
      transform: translateY(0) scale(1);
    }
  }
</style>

// src/routes/desktop/Dock.jsx
import React, { useState, useEffect, useRef, useCallback } from 'react';
import DockItemMagnified from './DockItemMagnified';
import Settings from '../apps/settings/Settings';
import Browser from '../apps/Browser';
import Terminal from '../apps/Terminal';
import Finder from '../apps/Finder';
import Papierkorb from '../apps/Trash';
import Apps from '../apps/Apps';
import Github from '../apps/Github';
import About from '../apps/About';
import Changelog from '../apps/Changelog';
import Galerie from '../apps/Galerie';
import Impressum from '../apps/Impressum';
import Agb from '../apps/AGB';
import Info from '../apps/Info';
import TerminalApp from '../apps/Terminal';
import Datenschutz from '../apps/Datenschutz';
import Model from '../apps/Model';
import CookiesInfo from '../apps/Cookies-info';
import { openTab, getCenterPosition } from '../../lib/openTab';
import { useTranslation } from '../../i18n/LanguageContext';
import './Dock.css';

const COMPONENT_MAP = {
  Finder, Apps, Settings, Browser, Terminal, Github, Papierkorb,
  About, Changelog, Galerie, Impressum, Agb, Info, Datenschutz, Model, CookiesInfo,
};

const DOCK_STORAGE_KEY = 'dock_pinned_apps_v1';

function loadPinnedApps() {
  try {
    const raw = localStorage.getItem(DOCK_STORAGE_KEY);
    if (raw) return JSON.parse(raw);
  } catch { }
  return [];
}

function savePinnedApps(apps) {
  const pinned = apps
    .filter((a) => !a.default)
    .map((a) => ({
      id: a.id,
      name: a.name,
      icon: a.icon,
      componentName: a.componentName || a.name,
      width: a.width,
      height: a.height,
    }));
  localStorage.setItem(DOCK_STORAGE_KEY, JSON.stringify(pinned));
}

const defaultApps = [
  { id: 1, name: 'Finder', icon: '/icons/finder.webp', open: false, minimized: false, maximized: false, component: Finder, default: true, x: 0, y: 0, width: 640, height: 400, zIndex: 0 },
  { id: 2, name: 'App Store', icon: '/icons/app-store.webp', open: false, minimized: false, maximized: false, component: Apps, default: true, x: 0, y: 0, width: 720, height: 480, zIndex: 0 },
  { id: 3, name: 'Settings', icon: '/icons/settings.webp', open: false, minimized: false, maximized: false, component: Settings, default: true, x: 0, y: 0, width: 460, height: 680, zIndex: 0 },
  { id: 4, name: 'Safari', icon: '/icons/safari.webp', open: false, minimized: false, maximized: false, component: Browser, default: true, x: 0, y: 0, width: 800, height: 500, zIndex: 0 },
  { id: 5, name: 'Terminal', icon: '/icons/terminal.webp', open: false, minimized: false, maximized: false, component: Terminal, default: true, x: 0, y: 0, width: 860, height: 480, zIndex: 0 },
  { id: 6, name: 'Github', icon: '/icons/github.webp', open: false, minimized: false, maximized: false, component: Github, default: true, x: 0, y: 0, width: 920, height: 600, zIndex: 0 },
  { id: 10, name: 'Trash', icon: '/icons/trash.webp', open: false, minimized: false, maximized: false, component: Papierkorb, default: true, x: 0, y: 0, width: 560, height: 360, zIndex: 0 },
];

function buildInitialApps() {
  const pinned = loadPinnedApps();
  const base = defaultApps.map((a) => ({ ...a }));

  const terminalIdx = base.findIndex((a) => a.id === 5);
  const insertIdx = terminalIdx !== -1 ? terminalIdx + 1 : base.length - 1;

  const restoredApps = pinned
    .filter((p) => !base.some((b) => b.id === p.id))
    .map((p) => ({
      id: p.id,
      name: p.name,
      icon: p.icon,
      component: COMPONENT_MAP[p.componentName] || null,
      componentName: p.componentName,
      default: false,
      open: false,
      minimized: false,
      maximized: false,
      x: 0,
      y: 0,
      width: p.width || 640,
      height: p.height || 400,
      zIndex: 0,
    }))
    .filter((a) => a.component);

  base.splice(insertIdx, 0, ...restoredApps);
  return base;
}

export default function Dock({ onOpenApp }) {
  const t = useTranslation();
  const [apps, setApps] = useState(() => buildInitialApps());
  const [contextMenu, setContextMenu] = useState(null);
  const [headerHeight] = useState(28);
  const [dockMouseX, setDockMouseX] = useState(null);
  const nextZIndex = useRef(10);
  const [enteringIds, setEnteringIds] = useState(new Set());
  const [draggingIds, setDraggingIds] = useState(new Set());
  const [minimizingIds, setMinimizingIds] = useState(new Set());
  const [restoringIds, setRestoringIds] = useState(new Set());

  useEffect(() => {
    savePinnedApps(apps);
  }, [apps]);

  const glassCardRef = useRef(null);
  const glassSpecularRef = useRef(null);

  const handleGlassMouseMove = useCallback((e) => {
    const card = glassCardRef.current;
    if (!card) return;
    const rect = card.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    const displace = document.querySelector('#glass-distortion feDisplacementMap');
    if (displace) {
      const scaleX = (x / rect.width) * 100;
      const scaleY = (y / rect.height) * 100;
      displace.setAttribute('scale', Math.min(scaleX, scaleY));
    }

    const spec = glassSpecularRef.current;
    if (spec) {
      spec.style.background = `radial-gradient(
        circle at ${x}px ${y}px,
        rgba(255,255,255,0.15) 0%,
        rgba(255,255,255,0.05) 30%,
        rgba(255,255,255,0) 60%
      )`;
    }
  }, []);

  const handleGlassMouseLeave = useCallback(() => {
    const displace = document.querySelector('#glass-distortion feDisplacementMap');
    if (displace) displace.setAttribute('scale', '77');

    const spec = glassSpecularRef.current;
    if (spec) spec.style.background = 'none';
  }, []);

  const focusedId = (() => {
    let best = null;
    let bestZ = -Infinity;
    for (const app of apps) {
      if (app.open && !app.minimized && app.zIndex > bestZ) {
        bestZ = app.zIndex;
        best = app.id;
      }
    }
    return best;
  })();

  const dragRef = useRef(null);
  const resizeRef = useRef(null);

  const handleMouseMove = useCallback((e) => {
    if (dragRef.current) {
      const { appId, startX, startY, origX, origY } = dragRef.current;
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      setApps((prev) =>
        prev.map((app) => {
          if (app.id !== appId) return app;
          const minVisible = 100;
          const newX = Math.max(-(app.width - minVisible), Math.min(window.innerWidth - minVisible, origX + dx));
          const newY = Math.max(headerHeight, Math.min(window.innerHeight - 50, origY + dy));
          return { ...app, x: newX, y: newY };
        })
      );
    }
    if (resizeRef.current) {
      const { appId, startX, startY, origW, origH } = resizeRef.current;
      const dx = e.clientX - startX;
      const dy = e.clientY - startY;
      setApps((prev) =>
        prev.map((app) =>
          app.id === appId
            ? { ...app, width: Math.max(200, origW + dx), height: Math.max(150, origH + dy) }
            : app
        )
      );
    }
  }, [headerHeight]);

  const handleMouseUp = useCallback(() => {
    if (dragRef.current) {
      const id = dragRef.current.appId;
      setDraggingIds((prev) => { const s = new Set(prev); s.delete(id); return s; });
    }
    if (resizeRef.current) {
      const id = resizeRef.current.appId;
      setDraggingIds((prev) => { const s = new Set(prev); s.delete(id); return s; });
    }
    dragRef.current = null;
    resizeRef.current = null;
  }, []);

  useEffect(() => {
    window.addEventListener('mousemove', handleMouseMove);
    window.addEventListener('mouseup', handleMouseUp);
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [handleMouseMove, handleMouseUp]);

  useEffect(() => {
    if (!contextMenu) return;
    const handler = () => setContextMenu(null);
    window.addEventListener('click', handler);
    return () => window.removeEventListener('click', handler);
  }, [contextMenu]);



  const focusApp = useCallback((id) => {
    nextZIndex.current += 1;
    setApps((prev) =>
      prev.map((app) =>
        app.id === id ? { ...app, zIndex: nextZIndex.current } : app
      )
    );
  }, []);

  const openApp = useCallback(
    (id) => {
      nextZIndex.current += 1;
      setApps((prev) =>
        prev.map((app) => {
          if (app.id !== id) return app;
          const opened = openTab({ ...app }, window.innerWidth, window.innerHeight);
          opened.zIndex = nextZIndex.current;
          return opened;
        })
      );
      if (onOpenApp) {
        const app = apps.find((a) => a.id === id);
        if (app) onOpenApp(app);
      }
    },
    [apps, onOpenApp]
  );

  const closeApp = useCallback((id) => {
    setMinimizingIds((s) => { const n = new Set(s); n.delete(id); return n; });
    setRestoringIds((s) => { const n = new Set(s); n.delete(id); return n; });
    setApps((prev) =>
      prev.map((app) =>
        app.id === id
          ? { ...app, open: false, minimized: false, maximized: false }
          : app
      )
    );
  }, []);

  const toggleMinimize = useCallback((id) => {
    setApps((prev) => {
      const app = prev.find((a) => a.id === id);
      if (!app) return prev;

      if (!app.minimized) {
        setMinimizingIds((s) => new Set(s).add(id));
        setTimeout(() => {
          setMinimizingIds((s) => { const n = new Set(s); n.delete(id); return n; });
          setApps((p) => p.map((a) => a.id === id ? { ...a, minimized: true } : a));
        }, 350);
        return prev;
      } else {
        setRestoringIds((s) => new Set(s).add(id));
        setTimeout(() => {
          setRestoringIds((s) => { const n = new Set(s); n.delete(id); return n; });
        }, 350);
        return prev.map((a) => a.id === id ? { ...a, minimized: false } : a);
      }
    });
  }, []);

  const toggleMaximize = useCallback((id) => {
    setApps((prev) =>
      prev.map((app) =>
        app.id === id ? { ...app, maximized: !app.maximized } : app
      )
    );
  }, []);

  const handleOpenApp = useCallback(
    (appOrName) => {
      if (typeof appOrName === 'string') {
        const existing = apps.find(
          (a) => a.name.toLowerCase() === appOrName.toLowerCase()
        );
        if (existing) openApp(existing.id);
        return;
      }

      const appData = appOrName;
      const pinOnly = !!appData.pinOnly;
      const existing = apps.find((a) => a.id === appData.id);
      if (existing) {
        if (!pinOnly) openApp(existing.id);
      } else {
        const componentName = Object.keys(COMPONENT_MAP).find(
          (k) => COMPONENT_MAP[k] === appData.component
        ) || appData.name;

        nextZIndex.current += 1;
        const newApp = {
          id: appData.id,
          name: appData.name,
          icon: appData.icon,
          component: appData.component,
          componentName,
          default: false,
          open: false,
          minimized: false,
          maximized: false,
          x: 0,
          y: 0,
          width: appData.width || 640,
          height: appData.height || 400,
          zIndex: 0,
        };
        setEnteringIds((prev) => new Set(prev).add(newApp.id));
        setTimeout(() => {
          setEnteringIds((prev) => { const s = new Set(prev); s.delete(newApp.id); return s; });
        }, 500);

        setApps((prev) => {
          const copy = [...prev];
          const termIdx = copy.findIndex((a) => a.id === 5);
          const insertIdx = termIdx !== -1 ? termIdx + 1 : copy.length - 1;
          if (copy.some((a) => a.id === newApp.id)) return prev;
          copy.splice(insertIdx, 0, newApp);
          return copy;
        });
        if (!pinOnly) setTimeout(() => openApp(appData.id), 0);
      }
    },
    [apps, openApp]
  );

  const handleDockContextMenu = useCallback((e, appId) => {
    e.preventDefault();
    setContextMenu({ appId, x: e.clientX, y: e.clientY });
  }, []);

  const closeContextMenu = useCallback(() => {
    setContextMenu(null);
  }, []);

  const handleContextAction = useCallback(
    (action) => {
      if (!contextMenu) return;
      const { appId } = contextMenu;
      switch (action) {
        case 'open':
          openApp(appId);
          break;
        case 'close':
          closeApp(appId);
          break;
        case 'minimize':
          toggleMinimize(appId);
          break;
        case 'maximize':
          toggleMaximize(appId);
          break;
        default:
          break;
      }
      closeContextMenu();
    },
    [contextMenu, openApp, closeApp, toggleMinimize, toggleMaximize, closeContextMenu]
  );

  const startDrag = useCallback(
    (e, id) => {
      e.preventDefault();
      focusApp(id);
      const app = apps.find((a) => a.id === id);
      if (!app) return;
      setDraggingIds((prev) => new Set(prev).add(id));
      dragRef.current = {
        appId: id,
        startX: e.clientX,
        startY: e.clientY,
        origX: app.x,
        origY: app.y,
      };
    },
    [apps, focusApp]
  );

  const startResize = useCallback(
    (e, id) => {
      e.preventDefault();
      e.stopPropagation();
      focusApp(id);
      const app = apps.find((a) => a.id === id);
      if (!app) return;
      setDraggingIds((prev) => new Set(prev).add(id));
      resizeRef.current = {
        appId: id,
        startX: e.clientX,
        startY: e.clientY,
        origW: app.width,
        origH: app.height,
      };
    },
    [apps, focusApp]
  );

  const withoutTrash = apps.filter((a) => a.id !== 10 && (a.default || !a.default));
  const trash = apps.filter((a) => a.id === 10);
  const sortedDockApps = [...withoutTrash, ...trash];

  return (
    <>
      
      {apps
        .filter((app) => app.open && (!app.minimized || minimizingIds.has(app.id)))
        .map((app) => {
          const isFocused = app.id === focusedId;
          const isMinimizing = minimizingIds.has(app.id);
          const isRestoring = restoringIds.has(app.id);
          const AppComponent = app.component;
          return (
            <div
              key={app.id}
              className={`app-window${app.maximized ? ' maximized' : ''}${isFocused ? ' focused' : ''}${draggingIds.has(app.id) ? ' no-transition' : ''}${isMinimizing ? ' minimizing' : ''}${isRestoring ? ' restoring' : ''}`}
              style={
                app.maximized
                  ? { left: 0, top: headerHeight, width: window.innerWidth, height: window.innerHeight - headerHeight - 85, zIndex: app.zIndex }
                  : { left: app.x, top: app.y, width: app.width, height: app.height, zIndex: app.zIndex }
              }
              onMouseDown={() => focusApp(app.id)}
            >
              <div
                className="title-bar"
                onMouseDown={(e) => !app.maximized && startDrag(e, app.id)}
                onDoubleClick={() => toggleMaximize(app.id)}
              >
                <div className="controls">
                  <button
                    className="ctrl close"
                    onClick={() => closeApp(app.id)}
                    aria-label="Close"
                  />
                  <button
                    className="ctrl minimize"
                    onClick={() => toggleMinimize(app.id)}
                    aria-label="Minimize"
                  />
                  <button
                    className="ctrl maximize"
                    onClick={() => toggleMaximize(app.id)}
                    aria-label="Maximize"
                  />
                </div>
                <span className="title-text">{app.name}</span>
              </div>
              <div className="window-content">
                <AppComponent onOpenApp={handleOpenApp} onClose={() => closeApp(app.id)} />
              </div>
              {!app.maximized && (
                <div
                  className="resizer"
                  onMouseDown={(e) => startResize(e, app.id)}
                />
              )}
            </div>
          );
        })}

      
      <svg style={{ display: 'none' }}>
        <filter id="glass-distortion">
          <feTurbulence type="turbulence" baseFrequency="0.008" numOctaves="2" result="noise" />
          <feDisplacementMap in="SourceGraphic" in2="noise" scale="77" />
        </filter>
      </svg>

      
      <div
        className="dock-container"
        onMouseMove={(e) => setDockMouseX(e.clientX)}
        onMouseLeave={() => setDockMouseX(null)}
      >
        <div
          className="glass-card"
          ref={glassCardRef}
          onMouseMove={handleGlassMouseMove}
          onMouseLeave={handleGlassMouseLeave}
        >
          <div className="glass-filter" />
          <div className="glass-overlay" />
          <div className="glass-specular" ref={glassSpecularRef} />
          <div className="glass-content">
            {sortedDockApps.map((app) => (
              <DockItemMagnified
                key={app.id}
                app_id={app.id}
                name={app.name}
                icon={app.icon}
                is_open={app.open}
                entering={enteringIds.has(app.id)}
                mouse_x={dockMouseX}
                onClick={() => (app.open ? (app.minimized ? toggleMinimize(app.id) : focusApp(app.id)) : openApp(app.id))}
                onContextMenu={(e) => handleDockContextMenu(e, app.id)}
              />
            ))}
          </div>
        </div>
      </div>

      
      {contextMenu && (
        <div
          className="context-menu-overlay"
          onClick={closeContextMenu}
        >
          <div
            className="context-menu"
            style={{ left: contextMenu.x, top: contextMenu.y }}
            onClick={(e) => e.stopPropagation()}
          >
            {(() => {
              const app = apps.find((a) => a.id === contextMenu.appId);
              if (!app) return null;
              return (
                <>
                  {!app.open && (
                    <button onClick={() => handleContextAction('open')}>{t('dock_open')}</button>
                  )}
                  {app.open && (
                    <>
                      <button onClick={() => handleContextAction('close')}>{t('dock_close')}</button>
                      <button onClick={() => handleContextAction('minimize')}>
                        {app.minimized ? t('dock_show') : t('dock_minimize')}
                      </button>
                      <button onClick={() => handleContextAction('maximize')}>
                        {app.maximized ? t('dock_restore') : t('dock_maximize')}
                      </button>
                    </>
                  )}
                </>
              );
            })()}
          </div>
        </div>
      )}
    </>
  );
}
